CREATE WAREHOUSE WH_DBTVAULT
    WITH WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME =TRUE;
    
USE WAREHOUSE WH_DBTVAULT;

CREATE DATABASE VAULT_DB;

USE DATABASE VAULT_DB;


CREATE SCHEMA RAW_DATA;

CREATE SCHEMA STAGING;

CREATE SCHEMA ANALYTICS;

CREATE SCHEMA VAULT;


CREATE OR REPLACE TABLE RAW_DATA.CUSTOMERS(

    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    CUSTOMER_TYPE VARCHAR,
    DATE_OF_BIRTH VARCHAR,
    EMAIL VARCHAR,
    ADDRESS VARCHAR,
    CREATED_AT VARCHAR,
    LOAD_DTS VARCHAR,
    RECORD_SOURCE VARCHAR
);


CREATE OR REPLACE TABLE RAW_DATA.ACCOUNT_DETAILS(
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR,
    OPEN_DATE VARCHAR,
    BRANCH_CODE VARCHAR,
    BALANCE VARCHAR,
    STATUS VARCHAR,
    LOAD_DTS VARCHAR,
    RECORD_SOURCE VARCHAR    
);


CREATE OR REPLACE TABLE RAW_DATA.TRANSACTION(
    TRANSACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    TRANSACTION_DATE VARCHAR,
    TRANSACTION_TYPE VARCHAR,
    AMOUNT VARCHAR,
    DESCRIPTION VARCHAR,
    LOAD_DTS VARCHAR,
    RECORD_SOURCE VARCHAR
    ); 



CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';


