name: 'dbt_vault_project'
version: '1.0.0'

config-version: 2

profile: 'banking_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:   
  dbt_vault_project:
    staging:
      +materialized: view
      +schema: STAGING

    analytics:
      +materialized: table
      +schema: Analytics  

    vaults:
      +materialized: incremental
      +schema: VAULT

    utils:
      +materialized: view
      +schema: STAGING
